version: 2.1

workflows:
  node-tests:
    jobs:
      - unit-tests:
          name: node13
          version: "13"
      - unit-tests:
          name: node14
          version: "14"
      - unit-tests:
          name: node15
          version: "15"
      - unit-tests:
          name: node16
          version: "16"
      - unit-tests:
          name: node18
          version: "18"
      - unit-tests:
          name: node-latest
          version: "latest"

jobs:
  unit-tests:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/node:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Versions
          command: |
            echo "npm: $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install typescript
          command: |
            npm install --no-save typescript
      - run:
          name: Run tests
          command: npm test