version: 2.1

workflows:
  node-tests:
    jobs:
      # The versions are copied from
      # https://circleci.com/developer/images/image/cimg/node#image-tags
      # End of Life (EOL): https://endoflife.date/nodejs
      - unit-tests:
          name: node16 # EOL 11 Sep 2023
          version: "16.18.1"
      - unit-tests:
          name: node18 # EOL 30 Apr 2025
          version: "18.17.1"
          requires:
            - node16
      - unit-tests:
          name: node20 # EOL 30 Apr 2026
          version: "20.5.1"
          requires:
            - node18
jobs:
  unit-tests:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/node:<< parameters.version >>
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm test
